### ISSUE TITLE
Consider adding Satin?

### ISSUE THREAD

**Issue by rezaali** [adamnemecek/awesome-metal#6]
Hi there! 

Awesome list! 

I wrote a small framework like threejs for Metal called [Satin](https://github.com/Hi-Rez/Satin). 

Its probably nothing, but it was I use to make all my [work](https://www.instagram.com/syedrezaali/).

Could be a good resource for learning.

**Comment by adamnemecek** [comment]
Want to submit a PR?

**Comment by rezaali** [comment]
Sure! Thanks for being open to it!
